# Generated by Django 6.0.4 on 2026-05-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_cinemahall_movie_moviesession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviesession',
            old_name='show_title',
            new_name='show_time',
        ),
    ]
